---
# Global variables - accessed by different roles and plays
#
tmp_dir: '/tmp/mosip' 
logs_dir: '{{tmp_dir}}/logs'
user_home: '{{lookup("env", "HOME")}}'
install_root: '{{user_home}}/shop-spree/spree/deployment/sandbox-v2'
charts_root: '{{install_root}}/helm/charts'  # Helm charts root
helm_cli_path: '{{user_home}}/bin'  # This path chosen as it is included in default $PATH in Centos 7.7

sandbox_domain_name: shop.beaswathitraders.net
site:
  sandbox_public_url: 'https://{{sandbox_domain_name}}'
  ssl:
    get_certificate: true  # get a fresh certificate for the domain using Letsencrypt.
    email: info@mosip.io
    certificate: '/etc/letsencrypt/live/{{sandbox_domain_name}}/fullchain.pem'
    certificate_key: '/etc/letsencrypt/live/{{sandbox_domain_name}}/privkey.pem'
   
is_glowroot: absent  # absent or present

docker_wait_time: 600   # Wait for docker to pull and deploy

clusters:
  mz:
    kube_config:  "{{lookup('env', 'HOME') }}/.kube/mzcluster.config" 
    nodeport_node: mzworker0.sb  # Any node on cluster for nodeport access
    any_node_ip: '10.20.20.157' # ip address of above node
    ingress:
      namespace: ingress-nginx
      nodeports:
        http: 30080 
        https: 30443
      base_url: 'http://{{groups["mzworkers"][0]}}:30080' # Any node since ingress runs on nodeport
    dashboard:
      url: /mz-dashboard
      token_file: '{{tmp_dir}}/dashboard_mz.token'
      token_expiry: 86400 # Seconds
      nodeport: 30081  # Dashboard runs on nodeport 
    monitoring:
      enabled: true
      namespace: monitoring
      nfs:
        server: '{{nfs.server}}'
        prometheus:
          alert_path: '{{nfs.folder}}/monitoring/mz/prometheus/alertmanager'
          push_path: '{{nfs.folder}}/monitoring/mz/prometheus/pushgateway'
          server_path: '{{nfs.folder}}/monitoring/mz/prometheus/server'
        grafana:
          path: '{{nfs.folder}}/monitoring/mz/grafana'
      grafana_ingress_path: 'mz-grafana'
      grafana_token_file: '{{tmp_dir}}/grafana_mz.token'
      elasticsearch:
        host: 'elasticsearch-master:9200'
      kibana: 
        url: http://kibana-kibana:5601 

# Postgres persistent storage
postgres:
  nfs_path: '{{nfs.folder}}/postgres'  
  size: 10Gi
  service_name: postgres # svc on Kubernetes
  service_port: 80
  server: '{{clusters.mz.nodeport_node}}'
  nodeport: 30090  # fixed for connecting from outside the cluster
  user: postgres
  password: postgres
  max_connections: 1000
  node_affinity: 
    enabled: false # To run postgres on an exclusive node
    node: 'mzworker0.sb' # Hostname. Run only on this node, and nothing else should run on this node
    taint:
      key: "postgres" # Key for applying taint on node
      value: "only"  

nfs:
  server: console.sb
  folder: /srv/nfs/mosip
